from datetime import timedelta
from .core.settings import settings

SECRET_KEY = settings.AUTH_SECRET_KEY
ALGORITHM = settings.AUTH_ALGORITHM
ACCESS_TOKEN_EXPIRE_MINUTES = int(settings.AUTH_ACCESS_TOKEN_EXPIRE_MINUTES)
OTP_EXP_MINUTES = int(settings.AUTH_OTP_EXP_MINUTES)

ACCESS_TOKEN_EXPIRE_DELTA = timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)

DATABASE_URL = settings.DATABASE_URL

SMTP_HOST = settings.SMTP_HOST
SMTP_PORT = int(settings.SMTP_PORT)
SMTP_USER = settings.SMTP_USER
SMTP_PASSWORD = settings.SMTP_PASSWORD
SMTP_FROM = settings.SMTP_FROM or settings.SMTP_USER
SMTP_FROM_NAME = settings.SMTP_FROM_NAME
